services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpass
      - DOCKER_INFLUXDB_INIT_ORG=GDDMuonCosmicStand
      - DOCKER_INFLUXDB_INIT_BUCKET=HV_Monitoring
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=QQnXxWkFZiDvqhiT31rRpFx8S6zqDrKyKJyBC550BJ5HcfxB26JYNzUeLKPjEJY4sy4PGnAxiwRcxzkJw_gqow==

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana

  pycaenhv:
    platform: linux/amd64
    build:
      context: ./pycaenhv-app
    image: yourusername/pycaenhv:latest
    depends_on:
      - influxdb
    volumes:
      - ./pycaenhv-app:/app
    environment:
      - INFLUXDB_HOST=influxdb
    env_file:
      - .env

volumes:
  influxdb-data:
  grafana-data:
